Dmx 3 configuration web UI
HendrikRauh/dmx-interface pull request #47
Opened 2024-12-15 17:53 UTC by RaffaelW

- control for the brightness of the LED
- extracted default values for the config, fixes #46 
- fixed input/output toggle
- disabled automatic wifi scan when the config page loads because it disconnects the wifi connection

2024-12-15 18:58 UTC, psxde requested changes
Bitte das DEFAULT_SUBNET auf /24. Für Station und Ethernet brauchen wir wohl eine andere IP, die dann die generierte 2. Adresse ist, hier passt auch die Subnetzmaske und das Gateway

2024-12-15 19:06 UTC, HendrikRauh requested changes
#46 is not fixed by this, leads to permanent disconnect from WiFi STA when config is saved without reselecting SSID. Possible cause: an empty SSID is written to config?

2024-12-15 19:07 UTC, HendrikRauh requested changes
Wifi scan only works on the second button press for me

On the first press the button only spins for a split second. On the second press it spins longer and i have a filled dropdown

2024-12-15 21:29 UTC, HendrikRauh commented on data/networks.js
> +                "ist, verbinde es bitte neu."
A bit much text. Would be nicer if it was shorter... But i don't know how to shorten it without removing information

2024-12-15 21:37 UTC, HendrikRauh commented on src/main.cpp
> +    WiFi.scanNetworks(true);
the caching works only inconsistent for me. Sometimes the dropdown is filled, sometimes not.

2024-12-15 21:42 UTC, HendrikRauh approved these changes
LGTM, 2 notes that could need work later

2024-12-15 21:42 UTC, psxde commented on data/networks.js
> +                "ist, verbinde es bitte neu."
hardwarebedingt würde ich zusammenschreiben. Sonst:
Beim WLAN-Scan wird die WLAN-Verbindung kurzzeitig unterbrochen. Möglicherweise musst du dich dann neu verbinden.

2024-12-15 21:44 UTC, psxde commented on src/main.cpp
> +    WiFi.scanNetworks(true);
Ich vermute, da können wir nicht wirklich was tun, außer erneut zu scannen. Ist die Frage, ob es das wert ist. Würde ich aber auch bei den anderen Projekten abgucken.

2024-12-16 20:27 UTC, HendrikRauh commented on src/routes/networks.cpp
> +#include "networks.h";
here should be no semicolon
```suggestion
#include "networks.h"
```

2024-12-16 20:32 UTC, merged